"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Navbar = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const utils_1 = require("../utils");
const Navbar = ({ brandName = 'PSC Tips & Tricks', links = [], user, onLogout, className, }) => {
    return ((0, jsx_runtime_1.jsx)("header", { className: (0, utils_1.cn)('sticky top-0 z-40 w-full border-b border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md', className), children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-8", children: [(0, jsx_runtime_1.jsx)("a", { href: "/", className: "flex items-center space-x-2 font-bold text-xl text-slate-900 dark:text-slate-100", children: (0, jsx_runtime_1.jsx)("span", { className: "bg-gradient-to-r from-indigo-600 to-amber-500 bg-clip-text text-transparent", children: brandName }) }), (0, jsx_runtime_1.jsx)("nav", { className: "hidden md:flex space-x-6", children: links.map((link) => ((0, jsx_runtime_1.jsx)("a", { href: link.href, className: (0, utils_1.cn)('text-sm font-medium transition-colors hover:text-indigo-600 dark:hover:text-indigo-400', link.active ? 'text-indigo-600 dark:text-indigo-400 font-semibold' : 'text-slate-600 dark:text-slate-400'), children: link.label }, link.href))) })] }), (0, jsx_runtime_1.jsx)("div", { className: "flex items-center space-x-4", children: user ? ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-3", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-sm font-medium text-slate-700 dark:text-slate-300 hidden sm:inline-block", children: user.name }), onLogout && ((0, jsx_runtime_1.jsx)("button", { onClick: onLogout, className: "text-xs text-rose-600 hover:text-rose-700 dark:text-rose-400 font-medium border border-rose-200 dark:border-rose-900 px-2.5 py-1 rounded-md", children: "Sign Out" }))] })) : ((0, jsx_runtime_1.jsxs)("div", { className: "flex items-center space-x-3", children: [(0, jsx_runtime_1.jsx)("a", { href: "/login", className: "text-sm font-medium text-slate-700 dark:text-slate-300 hover:text-indigo-600", children: "Log In" }), (0, jsx_runtime_1.jsx)("a", { href: "/signup", className: "text-sm font-semibold bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 shadow-sm", children: "Get Started" })] })) })] }) }));
};
exports.Navbar = Navbar;
