"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TableCell = exports.TableHead = exports.TableRow = exports.TableBody = exports.TableHeader = exports.Table = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const utils_1 = require("../utils");
const Table = ({ className, children, ...props }) => ((0, jsx_runtime_1.jsx)("div", { className: "w-full overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800", children: (0, jsx_runtime_1.jsx)("table", { className: (0, utils_1.cn)('w-full text-left text-sm text-slate-700 dark:text-slate-200', className), ...props, children: children }) }));
exports.Table = Table;
const TableHeader = ({ className, children, ...props }) => ((0, jsx_runtime_1.jsx)("thead", { className: (0, utils_1.cn)('bg-slate-50 dark:bg-slate-800/60 text-slate-900 dark:text-slate-100 font-semibold border-b border-slate-200 dark:border-slate-800', className), ...props, children: children }));
exports.TableHeader = TableHeader;
const TableBody = ({ className, children, ...props }) => ((0, jsx_runtime_1.jsx)("tbody", { className: (0, utils_1.cn)('divide-y divide-slate-200 dark:divide-slate-800 bg-white dark:bg-slate-900', className), ...props, children: children }));
exports.TableBody = TableBody;
const TableRow = ({ className, children, ...props }) => ((0, jsx_runtime_1.jsx)("tr", { className: (0, utils_1.cn)('hover:bg-slate-50/50 dark:hover:bg-slate-800/40 transition-colors', className), ...props, children: children }));
exports.TableRow = TableRow;
const TableHead = ({ className, children, ...props }) => ((0, jsx_runtime_1.jsx)("th", { className: (0, utils_1.cn)('px-4 py-3 text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400', className), ...props, children: children }));
exports.TableHead = TableHead;
const TableCell = ({ className, children, ...props }) => ((0, jsx_runtime_1.jsx)("td", { className: (0, utils_1.cn)('px-4 py-3 align-middle', className), ...props, children: children }));
exports.TableCell = TableCell;
