import * as Joi from 'joi';

export const configValidationSchema = Joi.object({
  PORT: Joi.number().default(4000),
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().default('super-secret-psc-jwt-key-2026'),
  JWT_REFRESH_SECRET: Joi.string().default('super-secret-psc-refresh-jwt-key-2026'),
  SUPABASE_URL: Joi.string().allow('').optional(),
  SUPABASE_SERVICE_ROLE_KEY: Joi.string().allow('').optional(),
  FRONTEND_URL: Joi.string().default('http://localhost:3000'),
  GOOGLE_CLIENT_ID: Joi.string().allow('').optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().allow('').optional(),
  GOOGLE_CALLBACK_URL: Joi.string().default('http://localhost:4000/auth/google/callback'),
  APPLE_CLIENT_ID: Joi.string().allow('').optional(),
  APPLE_TEAM_ID: Joi.string().allow('').optional(),
  APPLE_KEY_ID: Joi.string().allow('').optional(),
  APPLE_PRIVATE_KEY: Joi.string().allow('').optional(),
  APPLE_CALLBACK_URL: Joi.string().default('http://localhost:4000/auth/apple/callback'),
  RAZORPAY_KEY_ID: Joi.string().allow('').optional(),
  RAZORPAY_KEY_SECRET: Joi.string().allow('').optional(),
  RAZORPAY_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  RAZORPAY_MODE: Joi.string().valid('test', 'live', 'demo').default('test'),
  FFMPEG_PATH: Joi.string().default('ffmpeg'),
  WHISPER_CPP_BINARY_PATH: Joi.string().default('whisper-cli'),
  RNNOISE_MODEL_PATH: Joi.string().default('./models/rnnoise-model.rnnn'),
  WHISPER_MODEL_PATH: Joi.string().default('./models/ggml-small.bin'),
});
