import type { Metadata } from 'next';

/**
 * Single source of truth for search/social metadata. Server-only helpers live
 * here too (no localStorage, no auth), so route `layout.tsx` files and the
 * sitemap can fetch public catalog data without going through ApiClient.
 */

export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://psctipsandtricks.com').replace(/\/+$/, '');
export const SITE_NAME = 'PSC Tips And Tricks';
export const SITE_TAGLINE = 'Kerala PSC Exam Preparation — E-Books, Mock Tests & Quizzes';
export const DEFAULT_TITLE = `${SITE_NAME} — Kerala PSC E-Books, Mock Tests & Quizzes`;
export const DEFAULT_DESCRIPTION =
  'Prepare for Kerala PSC, SSC and other competitive exams with interactive e-books, teacher audio lessons, video classes, previous-year PDFs, chapter-wise quizzes and live mock tests with rank tracking.';

export const DEFAULT_KEYWORDS = [
  'Kerala PSC',
  'Kerala PSC coaching',
  'Kerala PSC exam preparation',
  'Kerala PSC mock test',
  'Kerala PSC online quiz',
  'Kerala PSC e-books',
  'Kerala PSC previous question papers',
  'PSC study materials Malayalam',
  'LDC exam preparation',
  'LGS exam preparation',
  'Degree level prelims',
  'SSC exam preparation',
  'PSC Tips And Tricks',
];

/** Generated by app/opengraph-image.tsx. */
export const DEFAULT_OG_IMAGE = { url: '/opengraph-image', width: 1200, height: 630, alt: DEFAULT_TITLE };

export const CONTACT_PHONE = '+91-8891930605';

const API_BASE_URL = (process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:4000').replace(/\/+$/, '');

export function absoluteUrl(path = '/'): string {
  if (/^https?:\/\//i.test(path)) return path;
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

/** Trim free-form text to a meta-description-sized snippet on a word boundary. */
export function toDescription(text: string | null | undefined, fallback = DEFAULT_DESCRIPTION, max = 160): string {
  const clean = (text || '').replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim();
  if (!clean) return fallback;
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  return `${cut.slice(0, Math.max(cut.lastIndexOf(' '), max - 30)).trimEnd()}…`;
}

const TITLE_TEMPLATE = `%s | ${SITE_NAME}`;

/**
 * Next only applies `title.template` from the nearest ancestor that declares
 * one, so a plain-string title in a nested layout would strip the brand from
 * every page below it. Spelling it out and re-declaring the template keeps
 * titles consistent at any depth.
 */
function brandedTitle(title: string): Metadata['title'] {
  const absolute = title.includes(SITE_NAME) ? title : TITLE_TEMPLATE.replace('%s', title);
  return { absolute, template: TITLE_TEMPLATE };
}

interface PageMetadataInput {
  title: string;
  description?: string;
  path: string;
  keywords?: string[];
  images?: { url: string; alt?: string; width?: number; height?: number }[];
  type?: 'website' | 'article' | 'book';
  noIndex?: boolean;
}

/** Per-page metadata with canonical URL, Open Graph and Twitter cards filled in consistently. */
export function pageMetadata({
  title,
  description = DEFAULT_DESCRIPTION,
  path,
  keywords,
  images = [DEFAULT_OG_IMAGE],
  type = 'website',
  noIndex = false,
}: PageMetadataInput): Metadata {
  return {
    title: brandedTitle(title),
    description,
    keywords: keywords ? Array.from(new Set([...keywords, ...DEFAULT_KEYWORDS])) : DEFAULT_KEYWORDS,
    alternates: { canonical: path },
    openGraph: {
      type: type === 'book' ? 'book' : type,
      url: path,
      siteName: SITE_NAME,
      title,
      description,
      locale: 'en_IN',
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: images.map((i) => i.url),
    },
    ...(noIndex ? { robots: { index: false, follow: false, googleBot: { index: false, follow: false } } } : {}),
  };
}

/** Metadata for account/transactional pages that should never appear in search results. */
export function privatePageMetadata(title: string): Metadata {
  return {
    title: brandedTitle(title),
    // Explicitly cleared so a private child page never inherits a parent's canonical.
    alternates: { canonical: null },
    robots: { index: false, follow: false, nocache: true, googleBot: { index: false, follow: false } },
  };
}

/**
 * Anonymous, cached fetch against the public API for metadata/sitemap use.
 * Returns null on any failure so a down API never breaks page rendering.
 */
export async function fetchPublic<T>(endpoint: string, revalidate = 3600): Promise<T | null> {
  try {
    const res = await fetch(`${API_BASE_URL}${endpoint}`, {
      next: { revalidate },
      headers: { Accept: 'application/json' },
    });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

/** Unwraps either a bare array or the `{ data: [...] }` pagination envelope. */
export function asList<T>(res: unknown): T[] {
  if (Array.isArray(res)) return res as T[];
  const data = (res as { data?: unknown } | null)?.data;
  return Array.isArray(data) ? (data as T[]) : [];
}

export function organizationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    '@id': `${SITE_URL}/#organization`,
    name: SITE_NAME,
    url: SITE_URL,
    logo: absoluteUrl('/icon-512.png'),
    description: DEFAULT_DESCRIPTION,
    areaServed: { '@type': 'State', name: 'Kerala', containedInPlace: { '@type': 'Country', name: 'India' } },
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: CONTACT_PHONE,
      contactType: 'customer support',
      areaServed: 'IN',
      availableLanguage: ['English', 'Malayalam'],
    },
  };
}

export function websiteJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE_URL}/#website`,
    name: SITE_NAME,
    alternateName: 'PSC Tips & Tricks',
    url: SITE_URL,
    inLanguage: ['en-IN', 'ml-IN'],
    publisher: { '@id': `${SITE_URL}/#organization` },
    potentialAction: {
      '@type': 'SearchAction',
      target: { '@type': 'EntryPoint', urlTemplate: `${SITE_URL}/books?search={search_term_string}` },
      'query-input': 'required name=search_term_string',
    },
  };
}

export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}
